version: "3.7"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    #image: joeriv/nginx-proxy-letsencrypt-swarm
    network_mode: bridge
    container_name: nginx-proxy
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs:ro
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
   # tags:
    #  - nginx
  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    network_mode: bridge
    container_name: nginx-proxy-letsencrypt
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
       #- "/media/data/docker/nginx/certs:/etc/nginx/certs:rw"
      - certs:/etc/nginx/certs:rw
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      #volumes_from: 
       # - nginx-proxy
       # tags:
        #  - nginx
  db:
    image: postgres:13
    network_mode: bridge
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_DB: Get2aha
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: p@ssw0rd@123
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:5.3
    network_mode: bridge
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: prahas.kattimani@pratian.com
      PGADMIN_DEFAULT_PASSWORD: pg@dmin@123
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db  
    links:
      - "db:db"
  get2aha:
    image: prahaskattimani/get2aha_fe-uat:31
    network_mode: bridge
    container_name: get2aha
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      VIRTUAL_HOST: portal.posmo.pratian.com #change it to your host
      LETSENCRYPT_HOST: portal.posmo.pratian.com #change it to your host
      LETSENCRYPT_EMAIL: prahas.kattimani@pratian.com #change it to your email
      VIRTUAL_PORT: "80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    #  - "/media/data/docker/candidate-profile:/usr/src/app"
    depends_on:
      - nginx-proxy
      - nginx-proxy-letsencrypt
  identity:
    image: prahaskattimani/identity-uat:6
    network_mode: bridge
    container_name: identity
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      VIRTUAL_HOST: identity.posmo.pratian.com #change it to your host
      LETSENCRYPT_HOST: identity.posmo.pratian.com #change it to your host
      LETSENCRYPT_EMAIL: prahas.kattimani@pratian.com #change it to your email
      VIRTUAL_PORT: "5002"
   # ports:
   #   - "5002:5002"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - nginx-proxy
      - nginx-proxy-letsencrypt
      - db
  client:
    image: prahaskattimani/client-uat:12
    container_name: client
    network_mode: bridge
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      VIRTUAL_HOST: client.posmo.pratian.com #change it to your host
      LETSENCRYPT_HOST: client.posmo.pratian.com #change it to your host
      LETSENCRYPT_EMAIL: prahas.kattimani@pratian.com #change it to your email
      VIRTUAL_PORT: "5001"
    ports:
      - "5001:5001"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - nginx-proxy
      - nginx-proxy-letsencrypt
      - db
    links:
      - "db:db"
  engagement:
    image: prahaskattimani/engagement-uat:21
    network_mode: bridge
    container_name: engagement
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      VIRTUAL_HOST: engagement.posmo.pratian.com #change it to your host
      LETSENCRYPT_HOST: engagement.posmo.pratian.com #change it to your host
      LETSENCRYPT_EMAIL: prahas.kattimani@pratian.com #change it to your email
      VIRTUAL_PORT: "5000"
    #ports:
      #- "5000:5000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" 
    depends_on:
      - nginx-proxy
      - nginx-proxy-letsencrypt
      - db
    links:
      - "db:db"
  admin:
    image: prahaskattimani/admin-uat:10
    network_mode: bridge
    container_name: admin
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      VIRTUAL_HOST: admin.posmo.pratian.com #change it to your host
      LETSENCRYPT_HOST: admin.posmo.pratian.com #change it to your host
      LETSENCRYPT_EMAIL: prahas.kattimani@pratian.com #change it to your email
      VIRTUAL_PORT: "5005"
    ports:
      - "5005:5005"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - nginx-proxy
      - nginx-proxy-letsencrypt
      - db
    links:
      - "db:db"  
  node_api:
    image: prahaskattimani/node-uat:4
    network_mode: bridge
    container_name: node_api
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      VIRTUAL_HOST: azure.posmo.pratian.com #change it to your host
      LETSENCRYPT_HOST: azure.posmo.pratian.com #change it to your host
      LETSENCRYPT_EMAIL: prahas.kattimani@pratian.com #change it to your email
      VIRTUAL_PORT: "5000"
   # ports:
   #   - "5000:5000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - nginx-proxy
      - nginx-proxy-letsencrypt      


volumes:
  certs:
  conf:
  vhost:
  html:
  acme:
  dhparam:
  pgadmin-data:
  db-data:  
